package com.app.wte.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Processing extends GridLayout {
	protected Label testRunName;
	protected Label processLbl;
	protected Label statusLbl;
	protected Label fileGenLbl;
	protected Label fail0;
	protected ProgressBar progressBar0;
	protected Label success0;
	protected Button downloadButton;
	protected Label fTPTransferLbl;
	protected Label fail1;
	protected ProgressBar progressBar1;
	protected Label success1;
	protected Label edge_to_RawLbl;
	protected Label fail2;
	protected ProgressBar progressBar2;
	protected Label success2;
	protected Label totalRecs_EdgeToRaw;
	protected Label validRecs_EdgeToRaw;
	protected Label invalidRecords_EdgeToRaw;
	protected Label rAW_To_RA;
	protected Label fail3;
	protected ProgressBar progressBar3;
	protected Label success3;
	protected Label totalRecs_RAWToRA;
	protected Label validRecs_RawToRa;
	protected Label invalidRecs_RawToRA;
	protected Label rA_to_RAW;
	protected Label fail4;
	protected ProgressBar progressBar4;
	protected Label success4;
	protected Label totalRecs_RAToRaw;
	protected Label validRecs_RAToRaw;
	protected Label invalidRecs_RAToRaw;
	protected Label rAW_To_R;
	protected Label fail5;
	protected ProgressBar progressBar5;
	protected Label success5;
	protected Label totalRecs_RawToR;
	protected Label validRecs_RawToR;
	protected Label invalidRecs_RawToR;
	protected Button testSuiteButton;

	public Processing() {
		Design.read(this);
	}
}
